# Generated by Django 2.1.5 on 2020-02-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='usr_profile',
            new_name='traveller',
        ),
    ]
