# Generated by Django 2.1.5 on 2020-02-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20200221_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='journey_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
