# Generated by Django 2.1.5 on 2020-02-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_auto_20200223_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeyorder',
            old_name='traveller',
            new_name='Journey',
        ),
    ]
