# Generated by Django 2.1.5 on 2020-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_auto_20200226_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeyorder',
            name='accepted_order_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
