# Generated by Django 2.1.5 on 2020-02-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_auto_20200226_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeyorder',
            old_name='Journey',
            new_name='journey',
        ),
    ]
