# Generated by Django 2.1.5 on 2020-03-24 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_negotiate'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiate',
            name='negotiation_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='negotiate',
            name='negotiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negotiate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.Order'),
        ),
    ]
