# Generated by Django 2.1.5 on 2020-03-24 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0011_auto_20200324_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiate',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiates', to='UserApp.Order'),
        ),
    ]
