# Generated by Django 2.1.5 on 2020-03-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0013_auto_20200325_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiate',
            name='price',
        ),
        migrations.AddField(
            model_name='negotiate',
            name='ngotiator_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='negotiate',
            name='orderer_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
