# Generated by Django 2.1.5 on 2020-03-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0015_auto_20200326_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='journey_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journeyorder',
            name='accepted_order_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='journeyorder',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_order', to='UserApp.Journey'),
        ),
    ]
