# Generated by Django 2.1.5 on 2020-05-26 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_auto_20200329_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negotiate',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='UserApp.Journey'),
        ),
    ]
