# Generated by Django 2.1.5 on 2020-06-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_auto_20200526_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('paymnt_gtway_name', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'Paypal')], max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='journeyorder',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserApp.Payment'),
        ),
    ]
