# Generated by Django 2.1.5 on 2020-06-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0021_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
    ]
