# Generated by Django 2.1.5 on 2020-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0025_auto_20200707_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiate',
            name='negotiation_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('accepted_by_negotiator', 'Accepted by Negotiator'), ('accepted_by_orderer', 'Accepted by Orderer'), ('rejected_by_orderer', 'Rejected by Orderer'), ('rejected_by_traveller', 'Rejected by Traveller'), ('cancelled', 'Cancelled')], max_length=50, null=True),
        ),
    ]
