# Generated by Django 2.1.5 on 2020-07-31 05:28

import UserApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0029_auto_20200731_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cyber_product_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_image',
            field=models.ImageField(null=True, upload_to=UserApp.models.Order.update_filename),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_to',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='package_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
